# Generated by Django 5.2.6 on 2025-09-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
