# Generated by Django 5.2.6 on 2025-11-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0007_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
