# Generated by Django 5.2.6 on 2025-11-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('region', models.TextField(default='Global')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.TextField(blank=True)),
                ('match_date', models.DateTimeField()),
                ('team_one_name', models.TextField(blank=True)),
                ('team_two_name', models.TextField(blank=True)),
                ('best_of', models.PositiveSmallIntegerField(default=3)),
                ('status', models.TextField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], default='upcoming')),
                ('team_one_score', models.PositiveSmallIntegerField(default=0)),
                ('team_two_score', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='project.gametitle')),
            ],
        ),
        migrations.CreateModel(
            name='ProPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.TextField(blank=True)),
                ('real_name', models.TextField(blank=True)),
                ('region', models.TextField(blank=True)),
                ('team_name', models.TextField(blank=True)),
                ('image_file', models.ImageField(blank=True, upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='project.gametitle')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.TextField(blank=True)),
                ('kills', models.PositiveSmallIntegerField()),
                ('deaths', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('acs', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='project.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='project.proplayer')),
            ],
            options={
                'unique_together': {('player', 'match', 'map_name')},
            },
        ),
    ]
