# Generated by Django 5.2.6 on 2025-12-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
