# Generated by Django 5.2.6 on 2025-12-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_match_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='external_id',
        ),
    ]
